# Generated by Django 5.2.8 on 2025-12-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earning_per_view', models.DecimalField(decimal_places=6, default=0.0025, max_digits=8)),
                ('min_withdrawal', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('site_name', models.CharField(default='dSkWala', max_length=100)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
