# Generated by Django 5.2.8 on 2025-12-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Bot ka naam (jaise TB Converter)', max_length=100)),
                ('description', models.TextField(help_text='Kya kaam karta hai ye bot')),
                ('telegram_username', models.CharField(help_text='@DiskWalaTBConverterBot', max_length=100)),
                ('telegram_link', models.URLField(help_text='https://t.me/DiskWalaTBConverterBot')),
                ('icon', models.CharField(default='link-2', help_text='Feather icon name', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
