# Generated by Django 5.2.8 on 2025-12-14 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_botlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='userfile',
            name='download_earnings',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userfile',
            name='downloads',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userfile',
            name='unique_downloads',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='fileview',
            index=models.Index(fields=['file', 'ip_address', 'viewed_at'], name='core_filevi_file_id_168d17_idx'),
        ),
        migrations.AddIndex(
            model_name='fileview',
            index=models.Index(fields=['viewed_at'], name='core_filevi_viewed__e3cdd1_idx'),
        ),
        migrations.AddField(
            model_name='filedownload',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_downloads', to='core.userfile'),
        ),
        migrations.AddIndex(
            model_name='filedownload',
            index=models.Index(fields=['file', 'ip_address', 'downloaded_at'], name='core_filedo_file_id_57c9f4_idx'),
        ),
        migrations.AddIndex(
            model_name='filedownload',
            index=models.Index(fields=['downloaded_at'], name='core_filedo_downloa_45bc19_idx'),
        ),
    ]
