# Generated by Django 5.2.8 on 2025-12-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_filedownload_userfile_download_earnings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='admob_banner_id',
            field=models.CharField(blank=True, default='ca-app-pub-3940256099942544/6300978111', help_text='AdMob Banner Ad Unit ID', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admob_interstitial_id',
            field=models.CharField(blank=True, default='ca-app-pub-3940256099942544/1033173712', help_text='AdMob Interstitial Ad Unit ID', max_length=100),
        ),
    ]
