# Generated by Django 5.2.8 on 2025-12-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_admob_banner_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfile',
            name='file',
        ),
        migrations.RemoveField(
            model_name='userfile',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='userfile',
            name='external_file_url',
            field=models.URLField(blank=True, default='', help_text='Direct ImageKit URL of the uploaded file', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userfile',
            name='external_thumbnail_url',
            field=models.URLField(blank=True, default='', help_text='ImageKit thumbnail URL (auto-generated for videos or custom)', max_length=500, null=True),
        ),
    ]
