# Generated by Django 5.2.8 on 2025-12-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_userfile_file_remove_userfile_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='meta_banner_placement_id',
            field=models.CharField(blank=True, default='', help_text='Meta Audience Network Banner Placement ID', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_interstitial_placement_id',
            field=models.CharField(blank=True, default='', help_text='Meta Audience Network Interstitial Placement ID', max_length=100),
        ),
    ]
