# Generated by Django 5.2.8 on 2025-12-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sitesettings_meta_banner_placement_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
