# Generated by Django 5.2.8 on 2025-12-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sitesettings_adsense_client_id_user_email_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='adsense_client_id',
            field=models.CharField(blank=True, default='', help_text='Google AdSense Client ID (ca-pub-XXXXXXXXXXXXXXXX)', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='discord',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, help_text='Personal website/blog', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
