# Generated by Django 5.2.8 on 2025-12-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_user_discord_alter_user_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_link',
            field=models.URLField(blank=True, default='', help_text='Instagram profile or channel full URL (e.g. https://www.instagram.com/yourprofile)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_link',
            field=models.URLField(blank=True, default='', help_text='Telegram channel or group full URL (e.g. https://t.me/yourchannel)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='youtube_link',
            field=models.URLField(blank=True, default='', help_text='YouTube channel full URL (e.g. https://www.youtube.com/@yourchannel)'),
        ),
    ]
