# Generated by Django 5.2.8 on 2025-12-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_sitesettings_instagram_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Notification message jo app mein dikhega')),
                ('link_url', models.URLField(blank=True, help_text='Optional link (khali chhodne par sirf message dikhega)', null=True)),
                ('link_text', models.CharField(blank=True, default='Open Link', help_text="Button ka text (jaise 'Visit Now')", max_length=50)),
                ('duration_days', models.IntegerField(choices=[(1, '1 Day'), (3, '3 Days'), (7, '7 Days'), (30, '30 Days'), (0, 'Forever')], default=7, help_text='Kitne din tak dikhega')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
