# Generated by Django 5.2.8 on 2025-12-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_broadcastnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='earning_per_download',
            field=models.DecimalField(decimal_places=6, default=0.001, help_text='Earning per unique download (e.g., 0.001000 = $1 per 1000 downloads)', max_digits=8),
        ),
    ]
