# Generated by Django 5.2.8 on 2025-12-27 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sitesettings_earning_per_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='payment_details',
            field=models.JSONField(default=dict, help_text='Details like UPI ID, Bank Account, IFSC etc. stored as JSON'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='payment_method',
            field=models.CharField(choices=[('upi', 'UPI'), ('bank', 'Bank Transfer')], default='upi', max_length=20),
        ),
    ]
