# Generated by Django 5.2.8 on 2026-01-06 19:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_withdrawal_payment_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='earning_per_1000_downloads',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='Earnings in USD per 1000 downloads', max_digits=8),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='earning_per_1000_views',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='Earnings in USD per 1000 views (e.g. 1.00 = $1 per 1K views)', max_digits=8),
        ),
    ]
