# Generated by Django 5.2.8 on 2026-01-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_sitesettings_earning_per_1000_downloads_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='seo_description',
            field=models.CharField(blank=True, default='Upload and share files securely. Earn money from views and downloads on Royaldisk.', max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_keywords',
            field=models.CharField(blank=True, default='file sharing, upload files, earn money online, secure cloud storage', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_og_image',
            field=models.URLField(blank=True, help_text='Default OG image URL for social sharing (e.g. logo or banner)', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_title',
            field=models.CharField(blank=True, default='Royaldisk - Fast & Secure File Sharing', max_length=200),
        ),
    ]
