# Generated by Django 5.2.8 on 2026-01-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_sitesettings_seo_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='favicon_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
