# Generated by Django 5.2.8 on 2026-01-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_sitesettings_favicon_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='custom_ad_script',
            field=models.TextField(blank=True, default='', help_text='Yahan third-party ad network ka pura <script>...</script> tag paste karo. Multiple scripts ke liye ek ke neeche ek likh sakte ho.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='custom_ad_script_enabled',
            field=models.BooleanField(default=False, help_text='Is checkbox ko tick karne par hi custom script load hoga'),
        ),
    ]
