# Generated by Django 5.1.15 on 2026-03-11 16:29

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DramaCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Drama Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Drama",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=220)),
                ("slug", models.SlugField(blank=True, max_length=260, unique=True)),
                (
                    "short_code",
                    models.CharField(
                        default=core.models.generate_short_code,
                        max_length=12,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "thumbnail_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("poster_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rejected_reason",
                    models.TextField(
                        blank=True, help_text="Reason if rejected by admin"
                    ),
                ),
                ("views", models.PositiveBigIntegerField(default=0)),
                ("total_episodes", models.PositiveIntegerField(default=0)),
                (
                    "earnings",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=12),
                ),
                (
                    "view_earnings",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=12),
                ),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_dramas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dramas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dramas",
                        to="drama.dramacategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-approved_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DramaEpisode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("episode_no", models.PositiveSmallIntegerField()),
                ("title", models.CharField(blank=True, max_length=220)),
                ("video_url", models.URLField(max_length=500)),
                (
                    "thumbnail_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("description", models.TextField(blank=True)),
                ("views", models.PositiveBigIntegerField(default=0)),
                (
                    "earnings",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
                ),
                (
                    "view_earnings",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "drama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        to="drama.drama",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "episode_no"],
            },
        ),
        migrations.CreateModel(
            name="DramaView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                ("view_date", models.DateField(auto_now_add=True)),
                (
                    "drama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_logs",
                        to="drama.drama",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EpisodeView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                ("view_date", models.DateField(auto_now_add=True)),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_logs",
                        to="drama.dramaepisode",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="drama",
            index=models.Index(
                fields=["status", "is_archived"], name="drama_drama_status_99585b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="drama",
            index=models.Index(
                fields=["user", "status"], name="drama_drama_user_id_86f895_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dramaepisode",
            index=models.Index(
                fields=["drama", "episode_no"], name="drama_drama_drama_i_37cc6e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dramaepisode",
            unique_together={("drama", "episode_no")},
        ),
        migrations.AddIndex(
            model_name="dramaview",
            index=models.Index(
                fields=["drama", "viewed_at"], name="drama_drama_drama_i_58bab0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dramaview",
            unique_together={("drama", "ip_address", "view_date")},
        ),
        migrations.AddIndex(
            model_name="episodeview",
            index=models.Index(
                fields=["episode", "viewed_at"], name="drama_episo_episode_742661_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="episodeview",
            unique_together={("episode", "ip_address", "view_date")},
        ),
    ]
